### ISSUE TITLE
Please How do i use this package to check my user registration progress and let them know in view blade

### ISSUE THREAD

**Issue by odion-cloud** [mtownsend5512/progress#2]
i want my user to know they have not finish there registration please How do i use it?

**Comment by mtownsend5512** [comment]
This is really something that you need to customize for your use case, this package just provides the API to manage steps and progress.

However, I can give you a brief example...

Controller:

    public function show()
    {
    	$progress = progress(
    		step($user->email_verified_at, 'Verified Email')->notNull()
    	);
    	$progress->get();

    	return view('account')->with([
    		'progress' => $progress
    	])
    }

In `account.blade.php`

``{{ $progress->percentage_complete }}``
